- .github/dependabot.yml
- .mergify.yml
- .yamllint.yml
- poe.toml
- poetry.lock
- pyproject.toml
- pytest_mergify/__init__.py
> ci: add yamllint

- pytest_mergify/__init__.py
- pytest_mergify/resources/github_actions.py
- tests/test_resources.py
> feat: add support for GHA resource attributes

- pytest_mergify/__init__.py
This avoids having an error with exporter not existing.
> fix: return if no repo name is found

- pytest_mergify/__init__.py
- pytest_mergify/tracer.py
- tests/conftest.py
- tests/test_plugin.py
- tests/test_resources.py
- tests/test_spans.py
This will allow to replace the MergifyTracer dynamically in tests for
easier scenario testing.
> refactor: split tracer setup code in its own part

- pytest_mergify/__init__.py
- pytest_mergify/tracer.py
- tests/test_plugin.py
This makes sure that if error while uploading are triggered they are
reported at the end of the test session. This makes it easier to debug
issues.
> feat: capture OpenTelemetry logs

- pytest_mergify/__init__.py
- tests/test_plugin.py
This is better than saying nothing has to be done.
> feat: print an error if repo name is not found

- pytest_mergify/__init__.py
- pytest_mergify/tracer.py
- tests/test_plugin.py
When running in complex test suite that mocks many things, trying to
flush in the background traces does not work. For example network
requests might be mocked, or time might be mocked, making SSL connection
impossible.
This stores the span in memory until a flush is requested at the end of
pytest.
This also means there is no way to capture the opentelemetry log in the
background are we can now intercept any error raised by the code while
flushing the traces.
> fix: disable async background flush of traces

- pytest_mergify/__init__.py
- tests/conftest.py
- tests/test_plugin.py
- tests/test_resources.py
- tests/test_spans.py
I found out you can actually pass plugin instance to pytester when
running it inline: this means we can grab the list of spans in a
sub-pytest if we run it inline.
This simplifies the overall architecture to split the tests in two mode:
- either we run them in a subprocess to test the whole lifecycle (e.g.
upload errors are printed)
- either we run them inprocess and we can read the list of spans
This will make it easier in the future to replace pytest-opentelemetry
and test the spans that are emitted.
> test: refactor plugin setup

- pytest_mergify/__init__.py
- tests/test_spans.py
This creates 3x more spans for each test which is too verbose.
> chore: remove setup/call/teardown steps

- tools/poetry-install.sh
> ci: use poetry sync and remove setuptools

- pytest_mergify/__init__.py
- tests/test_spans.py
> feat: add test.case.result.status

- tests/test_resources.py
- tests/test_spans.py
We moved this to be a tracer builtin.
> test: move resource test outside of resource

- pytest_mergify/__init__.py
- pytest_mergify/tracer.py
- tests/test_spans.py
OpenTelemetry does not know how to encode a 8 bytes integer in protobuf,
so it fails. Since the Python framework does not want us to use bytes,
we'll use a str with hex format.
> fix: set test.run.id as str

- pytest_mergify/__init__.py
- tests/test_spans.py
nodeid is too long as it contains the filename
> refactor: use node.name as name

- poetry.lock
- pyproject.toml
- pytest_mergify/tracer.py
- tests/conftest.py
- tests/test_plugin.py
The OTLPSpanExporter exporter ignores non-200 errors and does not print
anything. This makes sure we have an exception.
types-requests is not installable on Python 3.8 so we just ignore typing. Not a
big deal considering how we use requests here.
> fix: print errors on != 200

- pytest_mergify/__init__.py
help should be a `str` not a `tuple` otherwise it breaks `pytest --help`
Before the fix `pytest --help` is exiting with the following error
```
if action.help and action.help.strip():
^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'strip'
```
After the fix `pytest --help` is working as usual
> fix: pytest --help

- pytest_mergify/utils.py
- tests/test_plugin.py
CI=true is good to enable it by default in CI. But some tests may change
their behavior when CI is set.
For example in pytest, they use tox and ensure CI is not passed
to the test suite. Enabling pytest-mergify breaks the test suite.
This change introduces an alternative for user that can't rely
on CI=true.
> chore: add support PYTEST_MERGIFY_ENABLED=true

- pytest_mergify/ci_insights.py
- pytest_mergify/resources/git.py
- pytest_mergify/resources/jenkins.py
- pytest_mergify/utils.py
- tests/test_resources.py
Depending on how Jenkins checkout the code we may not have the GIT_*
envs.
This change creates a git provider that pick the data from the local
checked git.
> chore: add a git Detector

- pytest_mergify/ci_insights.py
- tests/test_ci_insights.py
Relates-To: MRGFY-5827
Depends-On: #189
> fix(ci-insights): Support all report outcomes when running flaky test detections

- pytest_mergify/ci_insights.py
- tests/test_ci_insights.py
The goal is to skip these tests and better be safe than sorry.
Relates-To: MRGFY-5917
> fix: Properly handle test with very long names in flaky detection
